export const AboutUsConstants = {
  title: 'Meet the Pack 🐾',
  description: 'Each team member is a sticker hero, crafting every detail with love.',
  teamCollaboration:
    'As a team, we collaborated closely through regular calls, a shared GitHub Projects board, and regular code reviews. Not only did we solve our own problems, we supported each other, debugged together, and refined ideas as a team — leading to a successful and enjoyable collaboration.',
  memberButtonTitle: 'Go to GitHub',
  buttonTitle: 'Start helping!',
  constibutionsTitle: 'Key project missions:',
  rssDescription:
    'RS School offers a unique learning experience as a free, community-based online education initiative. The RS School has been run by the Rolling Scopes community since 2013. Today, over 600 developer-volunteers from various countries and companies assist as mentors. We believe in important ideas that guide our mission.',
  rssUrl: 'https://rs.school/',
  rssButtonTitle: 'Learn more',
  members: [
    {
      name: '🐾 Anna',
      role: 'Team Lead & Frontend Developer',
      nickname: '@binary-apple',
      github: 'https://github.com/binary-apple',
      photo: '/images/binary-apple.webp',
      bio: 'Anna led the technical direction of the project and kept the whole team on track with care and attention to details. She kept the code clean and the team focused. 😻',
      contributions: [
        'Set up the Git repository, Deployment flow and Kanban board',
        'Built the main layout',
        'Developed the product catalog page',
        'Implemented navigation through categories and breadcrumbs',
        'Implemented filtering, searching and pagination',
        'Integrated product data from Commercetools',
        'Implemented core unit tests',
      ],
    },
    {
      name: '💡 Tetiana',
      role: 'Frontend Developer & Creative Spark',
      nickname: '@tanykos',
      github: 'https://github.com/tanykos',
      photo: '/images/tanykos.webp',
      bio: 'Tetiana combines strong front - end skills with a great sense of design.She writes clean, reusable code — and never misses a chance to make something look and work better. 🐾',
      contributions: [
        'Set up Commercetools project',
        'Implemented login and registration pages',
        'Integrated user authentication with Commercetools',
        'Developed the user profile page',
        'Implemented updating user information',
        'Built shopping cart page with its logic',
        'Implemented promo codes logic',
      ],
    },
    {
      name: '🧩 Alexey',
      role: 'Frontend Developer & Problem Solver',
      nickname: '@montaana01',
      github: 'https://github.com/montaana01',
      photo: '/images/montaana01.webp',
      bio: 'Alexey made the hard parts possible.He dived deep into both the infrastructure and the logic of the product.He simply built things that made everything else easier. 🧩',
      contributions: [
        'Configured linting, formatting, and pre - commit tools',
        'Collected real shelter data and generated stickers',
        'Built product cards, 404 and about us pages',
        'Implemented pricing(with and without discounts)',
        'Implemented cart API and token flow',
        'Created the product detail page with pictures slider',
        'Implemented core unit tests',
      ],
    },
  ],
};
